name: error_or
description: Return a result ErrorOr with either a value T or an error Object.
version: 0.3.0+1
homepage: https://github.com/erf/error_or

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
