name: error_or
description: A simple class for returning a value or an error
version: 0.0.1
homepage: github.com/erf/error_or

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
