name: error_or
description: Return a result ErrorOr with either a value T or an error Object.
version: 0.0.3
homepage: https://github.com/erf/error_or

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
